name: Terraform Apply

on:
  push:
    branches: [main]

jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    environment: AWS

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - uses: shmokmt/actions-setup-tfcmt@v2

      - name: Terraform Plan
        run: tfcmt plan -- terraform plan -input=false
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TF_VAR_AWS_ACCESS_KEY: ${{ secrets.TF_AWS_READONLY_ACCESSKEY }}
          TF_VAR_AWS_SECRET_KEY: ${{ secrets.TF_AWS_READONLY_SECRETKEY }}

      - name: Terraform Apply
        run: tfcmt apply -- terraform apply -input=false -auto-approve
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TF_VAR_AWS_ACCESS_KEY: ${{ secrets.TF_VAR_AWS_ACCESS_KEY }}
          TF_VAR_AWS_SECRET_KEY: ${{ secrets.TF_VAR_AWS_SECRET_KEY }}
