name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform_destroy:
    if: github.ref == 'refs/heads/main'
    uses: soat-tech-challenge/github-workflows/.github/workflows/terraform-destroy.yml@main
    secrets: inherit
